"""COBOL base integration patterns."""

from repo_surveyor.integration_patterns.types import (
    BasePatternSpec,
    Confidence,
    IntegrationType,
    PatternKey,
    SignalDirection,
)

BASE = BasePatternSpec(
    patterns={
        IntegrationType.HTTP_REST: {
            PatternKey.PATTERNS: [
                (
                    r"EXEC\s+CICS\s+WEB\s+",
                    Confidence.HIGH,
                    SignalDirection.INWARD,
                    (
                        "Web request is handled for inbound",
                        "HTTP request is handled inbound",
                    ),
                ),
                (
                    r"EXEC\s+CICS\s+INVOKE\s+WEBSERVICE",
                    Confidence.HIGH,
                    SignalDirection.OUTWARD,
                    (
                        "Web service is invoked for outbound call",
                        "Web service is called outbound",
                    ),
                ),
                (
                    r"DFHWS-",
                    Confidence.HIGH,
                    SignalDirection.AMBIGUOUS,
                    (
                        "Web service data areas are referenced by prefix",
                        "Web service is accessed",
                    ),
                ),
                (
                    r"WEB\s+SEND",
                    Confidence.HIGH,
                    SignalDirection.OUTWARD,
                    (
                        "HTTP response is sent to client",
                        "Web data is sent outbound",
                    ),
                ),
                (
                    r"WEB\s+RECEIVE",
                    Confidence.HIGH,
                    SignalDirection.INWARD,
                    (
                        "HTTP data is received from inbound request",
                        "Web data is received inbound",
                    ),
                ),
                (
                    r"URIMAP",
                    Confidence.MEDIUM,
                    SignalDirection.AMBIGUOUS,
                    (
                        "URI mapping is defined for resource",
                        "Web endpoint is accessed with URI mapping",
                    ),
                ),
                (
                    r"WEBSERVICE",
                    Confidence.MEDIUM,
                    SignalDirection.AMBIGUOUS,
                    (
                        "Web service is referenced by WEBSERVICE keyword",
                        "Web service is called",
                    ),
                ),
            ],
        },
        IntegrationType.SOAP: {
            PatternKey.PATTERNS: [
                (
                    r"EXEC\s+CICS\s+TRANSFORM",
                    Confidence.HIGH,
                    SignalDirection.AMBIGUOUS,
                    (
                        "XML data is converted with transform",
                        "SOAP message is transformed",
                    ),
                ),
                (
                    r"XML\s+PARSE",
                    Confidence.HIGH,
                    SignalDirection.AMBIGUOUS,
                    (
                        "XML document is parsed by XML PARSE statement",
                        "XML data is parsed for SOAP interaction",
                    ),
                ),
                (
                    r"XML\s+GENERATE",
                    Confidence.HIGH,
                    SignalDirection.AMBIGUOUS,
                    (
                        "XML document is generated by XML GENERATE statement",
                        "XML data is generated for SOAP interaction",
                    ),
                ),
                (
                    r"DFHWS2LS",
                    Confidence.HIGH,
                    SignalDirection.AMBIGUOUS,
                    (
                        "Web service is transformed to language structure",
                        "SOAP web service is accessed",
                    ),
                ),
                (
                    r"DFHLS2WS",
                    Confidence.HIGH,
                    SignalDirection.AMBIGUOUS,
                    (
                        "Language structure is transformed to web service",
                        "SOAP web service is accessed",
                    ),
                ),
                (
                    r"SOAPACTION",
                    Confidence.HIGH,
                    SignalDirection.AMBIGUOUS,
                    (
                        "SOAP action is referenced by header",
                        "SOAP web service is called",
                    ),
                ),
                (
                    r"WSDL",
                    Confidence.MEDIUM,
                    SignalDirection.AMBIGUOUS,
                    (
                        "SOAP service interface is described by WSDL reference",
                        "Web service is called with WSDL",
                    ),
                ),
            ],
        },
        IntegrationType.MESSAGING: {
            PatternKey.PATTERNS: [
                (
                    r"MQOPEN",
                    Confidence.HIGH,
                    SignalDirection.AMBIGUOUS,
                    (
                        "MQ queue is opened by MQOPEN",
                        "Message queue is accessed",
                    ),
                ),
                (
                    r"MQPUT",
                    Confidence.HIGH,
                    SignalDirection.OUTWARD,
                    (
                        "Message is produced to MQ queue",
                        "Messages are produced outbound",
                    ),
                ),
                (
                    r"MQGET",
                    Confidence.HIGH,
                    SignalDirection.INWARD,
                    (
                        "Message is consumed from MQ queue",
                        "Messages are received inbound",
                    ),
                ),
                (
                    r"MQCLOSE",
                    Confidence.HIGH,
                    SignalDirection.AMBIGUOUS,
                    (
                        "MQ queue handle is closed by MQCLOSE",
                        "Message queue is accessed",
                    ),
                ),
                (
                    r"MQCONN",
                    Confidence.HIGH,
                    SignalDirection.AMBIGUOUS,
                    (
                        "MQ queue manager connection is opened",
                        "Message broker connection is opened",
                    ),
                ),
                (
                    r"MQDISC",
                    Confidence.HIGH,
                    SignalDirection.AMBIGUOUS,
                    (
                        "MQ queue manager connection is closed",
                        "Message broker is accessed",
                    ),
                ),
                (
                    r"MQOD",
                    Confidence.HIGH,
                    SignalDirection.AMBIGUOUS,
                    (
                        "Object descriptor is structured for MQ",
                        "Message queue object is accessed",
                    ),
                ),
                (
                    r"MQMD",
                    Confidence.HIGH,
                    SignalDirection.AMBIGUOUS,
                    (
                        "Message descriptor is structured for MQ",
                        "Message metadata is accessed",
                    ),
                ),
                (
                    r"CMQC",
                    Confidence.HIGH,
                    SignalDirection.AMBIGUOUS,
                    (
                        "MQ constants are imported for messaging",
                        "Message queue is accessed",
                    ),
                ),
                (
                    r"EXEC\s+CICS\s+WRITEQ\s+TD",
                    Confidence.HIGH,
                    SignalDirection.OUTWARD,
                    (
                        "Transient data is written to queue",
                        "Transient data is produced outbound",
                    ),
                ),
                (
                    r"EXEC\s+CICS\s+READQ\s+TD",
                    Confidence.HIGH,
                    SignalDirection.INWARD,
                    (
                        "Transient data is read from queue",
                        "Transient data is received inbound",
                    ),
                ),
                (
                    r"EXEC\s+CICS\s+WRITEQ\s+TS",
                    Confidence.HIGH,
                    SignalDirection.OUTWARD,
                    (
                        "Temporary storage is written to queue",
                        "Temporary storage data is produced outbound",
                    ),
                ),
                (
                    r"EXEC\s+CICS\s+READQ\s+TS",
                    Confidence.HIGH,
                    SignalDirection.INWARD,
                    (
                        "Temporary storage is read from queue",
                        "Temporary storage data is received inbound",
                    ),
                ),
                (
                    r"EXEC\s+CICS\s+DEQ",
                    Confidence.MEDIUM,
                    SignalDirection.AMBIGUOUS,
                    (
                        "Resource lock is released with DEQ",
                        "Resource locking is managed",
                    ),
                ),
                (
                    r"EXEC\s+CICS\s+ENQ",
                    Confidence.MEDIUM,
                    SignalDirection.AMBIGUOUS,
                    (
                        "Resource lock is acquired with ENQ",
                        "Resource locking is managed",
                    ),
                ),
            ],
        },
        IntegrationType.SOCKET: {
            PatternKey.PATTERNS: [
                (
                    r"EZASOKET",
                    Confidence.HIGH,
                    SignalDirection.AMBIGUOUS,
                    (
                        "TCP socket API is accessed by program",
                        "Network socket is accessed via TCP/IP",
                    ),
                ),
                (
                    r"CALL\s+['\"]EZASOKET['\"]",
                    Confidence.HIGH,
                    SignalDirection.AMBIGUOUS,
                    (
                        "TCP socket API is invoked for networking",
                        "Network socket is accessed via TCP/IP",
                    ),
                ),
                (
                    r"SOCKET-",
                    Confidence.MEDIUM,
                    SignalDirection.AMBIGUOUS,
                    (
                        "Socket operation data is prefixed by area",
                        "Network socket is accessed",
                    ),
                ),
                (
                    r"TCPIP",
                    Confidence.MEDIUM,
                    SignalDirection.AMBIGUOUS,
                    (
                        "TCP/IP communication is referenced for network operations",
                        "TCP/IP network is accessed",
                    ),
                ),
                (
                    r"EXEC\s+CICS\s+EXTRACT\s+TCPIP",
                    Confidence.HIGH,
                    SignalDirection.INWARD,
                    (
                        "TCP client info is extracted from inbound",
                        "TCP/IP connection data is received inbound",
                    ),
                ),
                (
                    r"EXEC\s+CICS\s+SOCKET",
                    Confidence.HIGH,
                    SignalDirection.AMBIGUOUS,
                    (
                        "Socket operations are performed with command",
                        "Network socket is opened for communication",
                    ),
                ),
            ],
        },
        IntegrationType.DATABASE: {
            PatternKey.PATTERNS: [
                (
                    r"EXEC\s+SQL",
                    Confidence.HIGH,
                    SignalDirection.OUTWARD,
                    (
                        "Database is accessed by embedded SQL statement",
                        "Database is queried with embedded SQL",
                    ),
                ),
                (
                    r"SQLCA",
                    Confidence.HIGH,
                    SignalDirection.OUTWARD,
                    (
                        "SQL status is communicated by SQLCA area",
                        "Database is accessed with embedded SQL",
                    ),
                ),
                (
                    r"SQLCODE",
                    Confidence.HIGH,
                    SignalDirection.OUTWARD,
                    (
                        "SQL status is checked by SQLCODE field",
                        "Database is accessed with embedded SQL",
                    ),
                ),
                (
                    r"DCLGEN",
                    Confidence.HIGH,
                    SignalDirection.OUTWARD,
                    (
                        "Table declaration is generated for embedded SQL",
                        "Database table is accessed with embedded SQL",
                    ),
                ),
                (
                    r"INCLUDE\s+SQLCA",
                    Confidence.HIGH,
                    SignalDirection.OUTWARD,
                    (
                        "SQL communications area is imported by INCLUDE",
                        "Database is accessed with embedded SQL",
                    ),
                ),
                (
                    r"DECLARE\s+.*\s+CURSOR",
                    Confidence.HIGH,
                    SignalDirection.OUTWARD,
                    (
                        "Database cursor is declared for query processing",
                        "Database rows are queried with embedded SQL",
                    ),
                ),
                (
                    r"FETCH\s+.*\s+INTO",
                    Confidence.HIGH,
                    SignalDirection.OUTWARD,
                    (
                        "Database rows are fetched from cursor",
                        "Database rows are queried with embedded SQL",
                    ),
                ),
                (
                    r"SELECT\s+.*\s+INTO",
                    Confidence.HIGH,
                    SignalDirection.OUTWARD,
                    (
                        "Single database row is fetched by SELECT",
                        "Database is queried with embedded SQL",
                    ),
                ),
                (
                    r"INSERT\s+INTO",
                    Confidence.HIGH,
                    SignalDirection.OUTWARD,
                    (
                        "Database row is written by INSERT INTO",
                        "Database is written with embedded SQL",
                    ),
                ),
                (
                    r"UPDATE\s+.*\s+SET",
                    Confidence.HIGH,
                    SignalDirection.OUTWARD,
                    (
                        "Database rows are modified by UPDATE SET statement",
                        "Database is written with embedded SQL",
                    ),
                ),
                (
                    r"DELETE\s+FROM",
                    Confidence.HIGH,
                    SignalDirection.OUTWARD,
                    (
                        "Database rows are removed by DELETE FROM",
                        "Database is written with embedded SQL",
                    ),
                ),
                (
                    r"READ\s+.*\s+FILE",
                    Confidence.MEDIUM,
                    SignalDirection.AMBIGUOUS,
                    (
                        "VSAM file is read by READ statement",
                        "File-based data store is accessed",
                    ),
                ),
                (
                    r"WRITE\s+.*\s+FILE",
                    Confidence.MEDIUM,
                    SignalDirection.AMBIGUOUS,
                    (
                        "VSAM file is written by WRITE FILE statement",
                        "File-based data store is accessed",
                    ),
                ),
                (
                    r"REWRITE\s+.*\s+FILE",
                    Confidence.MEDIUM,
                    SignalDirection.AMBIGUOUS,
                    (
                        "File record is updated by REWRITE",
                        "File-based data store is accessed",
                    ),
                ),
                (
                    r"DELETE\s+.*\s+FILE",
                    Confidence.MEDIUM,
                    SignalDirection.AMBIGUOUS,
                    (
                        "File record is deleted by DELETE statement",
                        "File-based data store is accessed",
                    ),
                ),
                (
                    r"START\s+.*\s+FILE",
                    Confidence.MEDIUM,
                    SignalDirection.AMBIGUOUS,
                    (
                        "File cursor is positioned by START",
                        "File-based data store is accessed",
                    ),
                ),
                (
                    r"EXEC\s+CICS\s+READ",
                    Confidence.HIGH,
                    SignalDirection.OUTWARD,
                    (
                        "VSAM record is read from file",
                        "VSAM data store is queried",
                    ),
                ),
                (
                    r"EXEC\s+CICS\s+WRITE",
                    Confidence.HIGH,
                    SignalDirection.OUTWARD,
                    (
                        "VSAM record is written to file",
                        "VSAM data store is written",
                    ),
                ),
                (
                    r"EXEC\s+CICS\s+REWRITE",
                    Confidence.HIGH,
                    SignalDirection.OUTWARD,
                    (
                        "VSAM record is updated in file",
                        "VSAM data store is written",
                    ),
                ),
                (
                    r"EXEC\s+CICS\s+DELETE",
                    Confidence.HIGH,
                    SignalDirection.OUTWARD,
                    (
                        "VSAM record is deleted from file",
                        "VSAM data store is written",
                    ),
                ),
                (
                    r"EXEC\s+CICS\s+STARTBR",
                    Confidence.HIGH,
                    SignalDirection.OUTWARD,
                    (
                        "VSAM browse is started for records",
                        "VSAM data store is queried",
                    ),
                ),
                (
                    r"EXEC\s+CICS\s+READNEXT",
                    Confidence.HIGH,
                    SignalDirection.OUTWARD,
                    (
                        "Next VSAM record is read in browse",
                        "VSAM data store is queried",
                    ),
                ),
                (
                    r"EXEC\s+CICS\s+READPREV",
                    Confidence.HIGH,
                    SignalDirection.OUTWARD,
                    (
                        "Previous VSAM record is read in browse",
                        "VSAM data store is queried",
                    ),
                ),
                (
                    r"CALL\s+['\"]CBLTDLI['\"]",
                    Confidence.HIGH,
                    SignalDirection.OUTWARD,
                    (
                        "IMS database is invoked via DL/I calls",
                        "IMS database is queried with DL/I calls",
                    ),
                ),
                (
                    r"CALL\s+['\"]PLITDLI['\"]",
                    Confidence.HIGH,
                    SignalDirection.OUTWARD,
                    (
                        "IMS database is invoked via PL/I interface",
                        "IMS database is queried with DL/I calls",
                    ),
                ),
                (
                    r"CALL\s+['\"]AIBTDLI['\"]",
                    Confidence.HIGH,
                    SignalDirection.OUTWARD,
                    (
                        "IMS database is invoked via AIB interface",
                        "IMS database is queried with DL/I calls",
                    ),
                ),
                (
                    r"PCB\s+MASK",
                    Confidence.HIGH,
                    SignalDirection.OUTWARD,
                    (
                        "Communication block is defined by PCB MASK",
                        "IMS database is accessed",
                    ),
                ),
                (
                    r"SSA\s+AREA",
                    Confidence.MEDIUM,
                    SignalDirection.OUTWARD,
                    (
                        "Segment search argument is defined by SSA",
                        "IMS database segment is queried with DL/I calls",
                    ),
                ),
                (
                    r"IO-PCB",
                    Confidence.HIGH,
                    SignalDirection.OUTWARD,
                    (
                        "I/O communication block is defined for IMS",
                        "IMS database is accessed",
                    ),
                ),
                (
                    r"DB-PCB",
                    Confidence.HIGH,
                    SignalDirection.OUTWARD,
                    (
                        "Database communication block is defined for IMS",
                        "IMS database is accessed",
                    ),
                ),
                (
                    r"EXEC\s+IDMS",
                    Confidence.HIGH,
                    SignalDirection.OUTWARD,
                    (
                        "IDMS database operation is invoked by EXEC",
                        "Network database is queried",
                    ),
                ),
                (
                    r"BIND\s+RUN-UNIT",
                    Confidence.HIGH,
                    SignalDirection.OUTWARD,
                    (
                        "IDMS run unit is initialized by BIND",
                        "Network database connection is opened",
                    ),
                ),
                (
                    r"READY\s+\w+\s+USAGE-MODE",
                    Confidence.HIGH,
                    SignalDirection.OUTWARD,
                    (
                        "Database area is opened with usage mode",
                        "Database area is accessed",
                    ),
                ),
                (
                    r"FINISH\s+TASK",
                    Confidence.HIGH,
                    SignalDirection.OUTWARD,
                    (
                        "IDMS run unit is terminated by FINISH",
                        "Network database is accessed",
                    ),
                ),
                (
                    r"OBTAIN\s+(CALC|FIRST|NEXT|PRIOR|LAST|OWNER|WITHIN)",
                    Confidence.HIGH,
                    SignalDirection.OUTWARD,
                    (
                        "Record is retrieved from network database",
                        "Network database is queried",
                    ),
                ),
                (
                    r"FIND\s+CALC",
                    Confidence.HIGH,
                    SignalDirection.OUTWARD,
                    (
                        "Record is located by calculated key",
                        "Network database is queried",
                    ),
                ),
                (
                    r"FIND\s+FIRST\s+\w+\s+WITHIN",
                    Confidence.HIGH,
                    SignalDirection.OUTWARD,
                    (
                        "First set member is located by FIND",
                        "Database set is queried",
                    ),
                ),
                (
                    r"FIND\s+NEXT\s+\w+\s+WITHIN",
                    Confidence.HIGH,
                    SignalDirection.OUTWARD,
                    (
                        "Next set member is located by FIND",
                        "Database set is queried",
                    ),
                ),
                (
                    r"FIND\s+PRIOR",
                    Confidence.HIGH,
                    SignalDirection.OUTWARD,
                    (
                        "Previous set member is located by FIND",
                        "Database set is queried",
                    ),
                ),
                (
                    r"FIND\s+LAST",
                    Confidence.HIGH,
                    SignalDirection.OUTWARD,
                    (
                        "Last set member is located by FIND",
                        "Database set is queried",
                    ),
                ),
                (
                    r"FIND\s+OWNER",
                    Confidence.HIGH,
                    SignalDirection.OUTWARD,
                    (
                        "Set owner is located by FIND",
                        "Database set is queried",
                    ),
                ),
                (
                    r"FIND\s+\w+\s+WITHIN\s+\w+",
                    Confidence.HIGH,
                    SignalDirection.OUTWARD,
                    (
                        "Record is located within set by FIND",
                        "Database set is queried",
                    ),
                ),
                (
                    r"CONNECT\s+\w+\s+TO\s+\w+",
                    Confidence.HIGH,
                    SignalDirection.OUTWARD,
                    (
                        "Record is inserted into set by CONNECT",
                        "Database set is written",
                    ),
                ),
                (
                    r"DISCONNECT\s+\w+\s+FROM\s+\w+",
                    Confidence.HIGH,
                    SignalDirection.OUTWARD,
                    (
                        "Record is removed from set by DISCONNECT",
                        "Database set is written",
                    ),
                ),
                (
                    r"COMMIT\s+TASK",
                    Confidence.HIGH,
                    SignalDirection.OUTWARD,
                    (
                        "Database transaction is committed by IDMS",
                        "Network database is written",
                    ),
                ),
                (
                    r"ROLLBACK\s+TASK",
                    Confidence.HIGH,
                    SignalDirection.OUTWARD,
                    (
                        "Database transaction is rolled back by IDMS",
                        "Database transaction is managed",
                    ),
                ),
                (
                    r"IDMS-STATUS",
                    Confidence.HIGH,
                    SignalDirection.OUTWARD,
                    (
                        "Operation status is checked by IDMS field",
                        "Network database is accessed",
                    ),
                ),
                (
                    r"SUBSCHEMA-CTRL",
                    Confidence.HIGH,
                    SignalDirection.OUTWARD,
                    (
                        "IDMS subschema control is defined by SUBSCHEMA-CTRL area",
                        "Database subschema is accessed",
                    ),
                ),
                (
                    r"COPY\s+IDMS\s+",
                    Confidence.HIGH,
                    SignalDirection.OUTWARD,
                    (
                        "IDMS data definitions are imported by COPY statement",
                        "Network database is accessed",
                    ),
                ),
                (
                    r"SCHEMA\s+SECTION",
                    Confidence.HIGH,
                    SignalDirection.OUTWARD,
                    (
                        "Database schema references are defined by SCHEMA",
                        "Database schema is accessed",
                    ),
                ),
                (
                    r"DC\s+RETURN",
                    Confidence.HIGH,
                    SignalDirection.OUTWARD,
                    (
                        "Control is returned to IDMS DC",
                        "Online database task is accessed",
                    ),
                ),
                (
                    r"GET\s+SCRATCH",
                    Confidence.HIGH,
                    SignalDirection.OUTWARD,
                    (
                        "Scratch pad data is retrieved by GET",
                        "Scratch pad storage is queried",
                    ),
                ),
                (
                    r"PUT\s+SCRATCH",
                    Confidence.HIGH,
                    SignalDirection.OUTWARD,
                    (
                        "Scratch pad data is stored by PUT",
                        "Scratch pad storage is written",
                    ),
                ),
                (
                    r"TRANSFER\s+CONTROL\s+TO",
                    Confidence.HIGH,
                    SignalDirection.OUTWARD,
                    (
                        "Control is transferred to another program",
                        "Program is called outbound",
                    ),
                ),
                (
                    r"IDMS-DC",
                    Confidence.HIGH,
                    SignalDirection.OUTWARD,
                    (
                        "Data area is defined for IDMS DC",
                        "Online database task is accessed",
                    ),
                ),
            ],
        },
        IntegrationType.FILE_IO: {
            PatternKey.PATTERNS: [
                (
                    r"OPEN\s+INPUT",
                    Confidence.HIGH,
                    SignalDirection.AMBIGUOUS,
                    (
                        "File is opened for reading",
                        "File is read for input",
                    ),
                ),
                (
                    r"OPEN\s+OUTPUT",
                    Confidence.HIGH,
                    SignalDirection.AMBIGUOUS,
                    (
                        "File is opened for writing",
                        "File is written for output",
                    ),
                ),
                (
                    r"OPEN\s+I-O",
                    Confidence.HIGH,
                    SignalDirection.AMBIGUOUS,
                    (
                        "File is opened for bidirectional access",
                        "File is accessed for input/output",
                    ),
                ),
                (
                    r"\bREAD\b",
                    Confidence.MEDIUM,
                    SignalDirection.AMBIGUOUS,
                    (
                        "File record is read by READ statement",
                        "File is accessed",
                    ),
                ),
                (
                    r"\bWRITE\b",
                    Confidence.MEDIUM,
                    SignalDirection.AMBIGUOUS,
                    (
                        "File record is written by WRITE statement",
                        "File is accessed",
                    ),
                ),
                (
                    r"\bCLOSE\b",
                    Confidence.MEDIUM,
                    SignalDirection.AMBIGUOUS,
                    (
                        "File is closed after operations",
                        "File is accessed",
                    ),
                ),
                (
                    r"FD\s+",
                    Confidence.HIGH,
                    SignalDirection.AMBIGUOUS,
                    (
                        "File is declared by description entry",
                        "File is accessed",
                    ),
                ),
            ],
        },
    },
)
