"""COBOL base integration patterns."""

from repo_surveyor.integration_patterns.types import (
    BasePatternSpec,
    Confidence,
    IntegrationType,
    PatternKey,
    SignalDirection,
)

BASE = BasePatternSpec(
    patterns={
        IntegrationType.HTTP_REST: {
            PatternKey.PATTERNS: [
                (r"EXEC\s+CICS\s+WEB\s+", Confidence.HIGH, SignalDirection.INWARD),
                (
                    r"EXEC\s+CICS\s+INVOKE\s+WEBSERVICE",
                    Confidence.HIGH,
                    SignalDirection.OUTWARD,
                ),
                (r"DFHWS-", Confidence.HIGH, SignalDirection.AMBIGUOUS),
                (r"WEB\s+SEND", Confidence.HIGH, SignalDirection.OUTWARD),
                (r"WEB\s+RECEIVE", Confidence.HIGH, SignalDirection.INWARD),
                (r"URIMAP", Confidence.MEDIUM, SignalDirection.AMBIGUOUS),
                (r"WEBSERVICE", Confidence.MEDIUM, SignalDirection.AMBIGUOUS),
            ],
        },
        IntegrationType.SOAP: {
            PatternKey.PATTERNS: [
                (
                    r"EXEC\s+CICS\s+TRANSFORM",
                    Confidence.HIGH,
                    SignalDirection.AMBIGUOUS,
                ),
                (r"XML\s+PARSE", Confidence.HIGH, SignalDirection.AMBIGUOUS),
                (r"XML\s+GENERATE", Confidence.HIGH, SignalDirection.AMBIGUOUS),
                (r"DFHWS2LS", Confidence.HIGH, SignalDirection.AMBIGUOUS),
                (r"DFHLS2WS", Confidence.HIGH, SignalDirection.AMBIGUOUS),
                (r"SOAPACTION", Confidence.HIGH, SignalDirection.AMBIGUOUS),
                (r"WSDL", Confidence.MEDIUM, SignalDirection.AMBIGUOUS),
            ],
        },
        IntegrationType.MESSAGING: {
            PatternKey.PATTERNS: [
                (r"MQOPEN", Confidence.HIGH, SignalDirection.AMBIGUOUS),
                (r"MQPUT", Confidence.HIGH, SignalDirection.OUTWARD),
                (r"MQGET", Confidence.HIGH, SignalDirection.INWARD),
                (r"MQCLOSE", Confidence.HIGH, SignalDirection.AMBIGUOUS),
                (r"MQCONN", Confidence.HIGH, SignalDirection.AMBIGUOUS),
                (r"MQDISC", Confidence.HIGH, SignalDirection.AMBIGUOUS),
                (r"MQOD", Confidence.HIGH, SignalDirection.AMBIGUOUS),
                (r"MQMD", Confidence.HIGH, SignalDirection.AMBIGUOUS),
                (r"CMQC", Confidence.HIGH, SignalDirection.AMBIGUOUS),
                (
                    r"EXEC\s+CICS\s+WRITEQ\s+TD",
                    Confidence.HIGH,
                    SignalDirection.OUTWARD,
                ),
                (r"EXEC\s+CICS\s+READQ\s+TD", Confidence.HIGH, SignalDirection.INWARD),
                (
                    r"EXEC\s+CICS\s+WRITEQ\s+TS",
                    Confidence.HIGH,
                    SignalDirection.OUTWARD,
                ),
                (r"EXEC\s+CICS\s+READQ\s+TS", Confidence.HIGH, SignalDirection.INWARD),
                (r"EXEC\s+CICS\s+DEQ", Confidence.MEDIUM, SignalDirection.AMBIGUOUS),
                (r"EXEC\s+CICS\s+ENQ", Confidence.MEDIUM, SignalDirection.AMBIGUOUS),
            ],
        },
        IntegrationType.SOCKET: {
            PatternKey.PATTERNS: [
                (r"EZASOKET", Confidence.HIGH, SignalDirection.AMBIGUOUS),
                (
                    r"CALL\s+['\"]EZASOKET['\"]",
                    Confidence.HIGH,
                    SignalDirection.AMBIGUOUS,
                ),
                (r"SOCKET-", Confidence.MEDIUM, SignalDirection.AMBIGUOUS),
                (r"TCPIP", Confidence.MEDIUM, SignalDirection.AMBIGUOUS),
                (
                    r"EXEC\s+CICS\s+EXTRACT\s+TCPIP",
                    Confidence.HIGH,
                    SignalDirection.INWARD,
                ),
                (r"EXEC\s+CICS\s+SOCKET", Confidence.HIGH, SignalDirection.AMBIGUOUS),
            ],
        },
        IntegrationType.DATABASE: {
            PatternKey.PATTERNS: [
                (r"EXEC\s+SQL", Confidence.HIGH, SignalDirection.OUTWARD),
                (r"SQLCA", Confidence.HIGH, SignalDirection.OUTWARD),
                (r"SQLCODE", Confidence.HIGH, SignalDirection.OUTWARD),
                (r"DCLGEN", Confidence.HIGH, SignalDirection.OUTWARD),
                (r"INCLUDE\s+SQLCA", Confidence.HIGH, SignalDirection.OUTWARD),
                (r"DECLARE\s+.*\s+CURSOR", Confidence.HIGH, SignalDirection.OUTWARD),
                (r"FETCH\s+.*\s+INTO", Confidence.HIGH, SignalDirection.OUTWARD),
                (r"SELECT\s+.*\s+INTO", Confidence.HIGH, SignalDirection.OUTWARD),
                (r"INSERT\s+INTO", Confidence.HIGH, SignalDirection.OUTWARD),
                (r"UPDATE\s+.*\s+SET", Confidence.HIGH, SignalDirection.OUTWARD),
                (r"DELETE\s+FROM", Confidence.HIGH, SignalDirection.OUTWARD),
                (r"READ\s+.*\s+FILE", Confidence.MEDIUM, SignalDirection.AMBIGUOUS),
                (r"WRITE\s+.*\s+FILE", Confidence.MEDIUM, SignalDirection.AMBIGUOUS),
                (r"REWRITE\s+.*\s+FILE", Confidence.MEDIUM, SignalDirection.AMBIGUOUS),
                (r"DELETE\s+.*\s+FILE", Confidence.MEDIUM, SignalDirection.AMBIGUOUS),
                (r"START\s+.*\s+FILE", Confidence.MEDIUM, SignalDirection.AMBIGUOUS),
                (r"EXEC\s+CICS\s+READ", Confidence.HIGH, SignalDirection.OUTWARD),
                (r"EXEC\s+CICS\s+WRITE", Confidence.HIGH, SignalDirection.OUTWARD),
                (r"EXEC\s+CICS\s+REWRITE", Confidence.HIGH, SignalDirection.OUTWARD),
                (r"EXEC\s+CICS\s+DELETE", Confidence.HIGH, SignalDirection.OUTWARD),
                (r"EXEC\s+CICS\s+STARTBR", Confidence.HIGH, SignalDirection.OUTWARD),
                (r"EXEC\s+CICS\s+READNEXT", Confidence.HIGH, SignalDirection.OUTWARD),
                (r"EXEC\s+CICS\s+READPREV", Confidence.HIGH, SignalDirection.OUTWARD),
                (r"CALL\s+['\"]CBLTDLI['\"]", Confidence.HIGH, SignalDirection.OUTWARD),
                (r"CALL\s+['\"]PLITDLI['\"]", Confidence.HIGH, SignalDirection.OUTWARD),
                (r"CALL\s+['\"]AIBTDLI['\"]", Confidence.HIGH, SignalDirection.OUTWARD),
                (r"PCB\s+MASK", Confidence.HIGH, SignalDirection.OUTWARD),
                (r"SSA\s+AREA", Confidence.MEDIUM, SignalDirection.OUTWARD),
                (r"IO-PCB", Confidence.HIGH, SignalDirection.OUTWARD),
                (r"DB-PCB", Confidence.HIGH, SignalDirection.OUTWARD),
                (r"EXEC\s+IDMS", Confidence.HIGH, SignalDirection.OUTWARD),
                (r"BIND\s+RUN-UNIT", Confidence.HIGH, SignalDirection.OUTWARD),
                (
                    r"READY\s+\w+\s+USAGE-MODE",
                    Confidence.HIGH,
                    SignalDirection.OUTWARD,
                ),
                (r"FINISH\s+TASK", Confidence.HIGH, SignalDirection.OUTWARD),
                (
                    r"OBTAIN\s+(CALC|FIRST|NEXT|PRIOR|LAST|OWNER|WITHIN)",
                    Confidence.HIGH,
                    SignalDirection.OUTWARD,
                ),
                (r"FIND\s+CALC", Confidence.HIGH, SignalDirection.OUTWARD),
                (
                    r"FIND\s+FIRST\s+\w+\s+WITHIN",
                    Confidence.HIGH,
                    SignalDirection.OUTWARD,
                ),
                (
                    r"FIND\s+NEXT\s+\w+\s+WITHIN",
                    Confidence.HIGH,
                    SignalDirection.OUTWARD,
                ),
                (r"FIND\s+PRIOR", Confidence.HIGH, SignalDirection.OUTWARD),
                (r"FIND\s+LAST", Confidence.HIGH, SignalDirection.OUTWARD),
                (r"FIND\s+OWNER", Confidence.HIGH, SignalDirection.OUTWARD),
                (
                    r"FIND\s+\w+\s+WITHIN\s+\w+",
                    Confidence.HIGH,
                    SignalDirection.OUTWARD,
                ),
                (r"CONNECT\s+\w+\s+TO\s+\w+", Confidence.HIGH, SignalDirection.OUTWARD),
                (
                    r"DISCONNECT\s+\w+\s+FROM\s+\w+",
                    Confidence.HIGH,
                    SignalDirection.OUTWARD,
                ),
                (r"COMMIT\s+TASK", Confidence.HIGH, SignalDirection.OUTWARD),
                (r"ROLLBACK\s+TASK", Confidence.HIGH, SignalDirection.OUTWARD),
                (r"IDMS-STATUS", Confidence.HIGH, SignalDirection.OUTWARD),
                (r"SUBSCHEMA-CTRL", Confidence.HIGH, SignalDirection.OUTWARD),
                (r"COPY\s+IDMS\s+", Confidence.HIGH, SignalDirection.OUTWARD),
                (r"SCHEMA\s+SECTION", Confidence.HIGH, SignalDirection.OUTWARD),
                (r"DC\s+RETURN", Confidence.HIGH, SignalDirection.OUTWARD),
                (r"GET\s+SCRATCH", Confidence.HIGH, SignalDirection.OUTWARD),
                (r"PUT\s+SCRATCH", Confidence.HIGH, SignalDirection.OUTWARD),
                (r"TRANSFER\s+CONTROL\s+TO", Confidence.HIGH, SignalDirection.OUTWARD),
                (r"IDMS-DC", Confidence.HIGH, SignalDirection.OUTWARD),
            ],
        },
        IntegrationType.FILE_IO: {
            PatternKey.PATTERNS: [
                (r"OPEN\s+INPUT", Confidence.HIGH, SignalDirection.AMBIGUOUS),
                (r"OPEN\s+OUTPUT", Confidence.HIGH, SignalDirection.AMBIGUOUS),
                (r"OPEN\s+I-O", Confidence.HIGH, SignalDirection.AMBIGUOUS),
                (r"\bREAD\b", Confidence.MEDIUM, SignalDirection.AMBIGUOUS),
                (r"\bWRITE\b", Confidence.MEDIUM, SignalDirection.AMBIGUOUS),
                (r"\bCLOSE\b", Confidence.MEDIUM, SignalDirection.AMBIGUOUS),
                (r"FD\s+", Confidence.HIGH, SignalDirection.AMBIGUOUS),
            ],
        },
    },
)
